# Generated by Django 4.2.5 on 2023-09-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0002_scheduledjob_is_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledjob',
            name='is_running',
        ),
    ]
