# Generated by Django 4.2.5 on 2023-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('first_contentful_paint', models.FloatField()),
                ('largest_contentful_paint', models.FloatField()),
                ('total_blocking_time', models.FloatField()),
                ('seo_score', models.PositiveIntegerField()),
                ('best_practice_score', models.PositiveIntegerField()),
                ('accessibility_score', models.PositiveIntegerField()),
            ],
        ),
    ]
