# Generated by Django 4.2.5 on 2023-09-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('seo_score', models.FloatField(blank=True, null=True)),
                ('best_practice_score', models.FloatField(blank=True, null=True)),
                ('accessibility_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
