# Generated by Django 4.2.5 on 2023-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagescore',
            name='first_contentful_paint',
            field=models.FloatField(null=True),
        ),
    ]
