# Generated by Django 4.2.5 on 2023-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_checker', '0002_alter_pagescore_first_contentful_paint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagescore',
            name='largest_contentful_paint',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pagescore',
            name='total_blocking_time',
            field=models.FloatField(null=True),
        ),
    ]
