# Generated by Django 4.2.5 on 2023-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_checker', '0003_alter_pagescore_largest_contentful_paint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagescore',
            name='accessibility_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pagescore',
            name='best_practice_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pagescore',
            name='seo_score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
