# Generated by Django 4.2.5 on 2023-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_checker', '0004_alter_pagescore_accessibility_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagescore',
            name='performance_score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
